# Do not commit private keys. Put AGE private key in ~/.config/sops/age/keys.txt
creation_rules:
  - path_regex: secrets/.*\.(yaml|yml|json|env)$
    encrypted_regex: '^(data|stringData|password|secret|token)$'
    age:
      - age1uvta2fsrsqekkgyw5rjxha3uje2dnazte6kvqqrc88g83zdrfarqwqy0nl
